package com.banditgames.platform.acl.adapter.web;

import com.banditgames.platform.acl.adapter.messaging.chess.ChessGameRegisteredMessage;
import com.banditgames.platform.acl.adapter.web.dto.ChessGameRegistrationRequest;
import com.banditgames.platform.acl.adapter.web.dto.ChessGameRegistrationResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * REST controller for chess game integration via ACL.
 * 
 * This controller handles registration of the external chess game with the platform.
 * Game state operations are handled by game-service via API Gateway ACL transformation.
 * 
 * Flow:
 * - Registration: Chess Game → API Gateway → Platform Backend (stores metadata)
 * - Game Operations: Chess Game → API Gateway → Game Service (via ACL transformation)
 * 
 * Endpoints are accessible via API Gateway at /api/external/chess/**
 * 
 * Note: Most chess game REST operations are routed directly to game-service by API Gateway.
 * This controller primarily handles registration and metadata operations.
 */
@Slf4j
@RestController
@RequestMapping("/api/external/chess")
@RequiredArgsConstructor
public class ChessGameController {

    private final RabbitTemplate rabbitTemplate;

    @Value("${chess.game.exchange.name:gameExchange}")
    private String chessExchangeName;

    /**
     * Register a chess game with the platform.
     * 
     * This endpoint is called via API Gateway after the gateway generates a gameId.
     * The endpoint:
     * 1. Creates a registration record
     * 2. Publishes a GameRegisteredMessage to RabbitMQ with routing key "game.registered"
     * 3. Returns the registration response
     * 
     * @param gameId The chess game ID (generated by gateway)
     * @param request Registration request with frontend URL
     * @return Registration response
     */
    @PostMapping("/register/{gameId}")
    public ResponseEntity<ChessGameRegistrationResponse> registerChessGame(
            @PathVariable UUID gameId,
            @RequestBody ChessGameRegistrationRequest request) {
        
        log.info("ACL: Registering chess game - gameId={}, frontendUrl={}", 
                gameId, request.getFrontendUrl());
        
        try {
            // Generate registration ID
            UUID registrationId = UUID.randomUUID();
            
            // Create the RabbitMQ message
            ChessGameRegisteredMessage message = new ChessGameRegisteredMessage();
            message.setRegistrationId(registrationId);
            message.setFrontendUrl(request.getFrontendUrl());
            message.setPictureUrl(request.getPictureUrl());
            message.setMessageType("GAME_REGISTERED");
            message.setTimestamp(new Date());
            
            // Define available chess achievements
            List<ChessGameRegisteredMessage.ChessAchievement> achievements = new ArrayList<>();
            achievements.add(createAchievement("FIRST_BLOOD", "Capture your opponent's first piece"));
            achievements.add(createAchievement("PAWN_POWER", "Promoted a pawn"));
            achievements.add(createAchievement("SPEEDY_VICTORY", "Win in under 20 moves"));
            achievements.add(createAchievement("SPEED_DEMON", "Make a move in under 5 seconds"));
            achievements.add(createAchievement("WINNER_WINNER_CHICKEN_DINNER", "Winner winner chicken dinner"));
            achievements.add(createAchievement("CASTLE_TIME", "Castle kingside or queenside"));
            achievements.add(createAchievement("ROOKIE_MOVE", "Move your rook for the first time"));
            achievements.add(createAchievement("PAWN_STORM", "Make 3 pawn moves in a row"));
            message.setAvailableAchievements(achievements);
            
            // Publish to RabbitMQ with routing key "game.registered"
            rabbitTemplate.convertAndSend(
                    chessExchangeName,
                    "game.registered",
                    message
            );
            
            log.info("ACL: Published chess game registered event - gameId={}, registrationId={}, exchange={}, routingKey=game.registered", 
                    gameId, registrationId, chessExchangeName);
            
            // Create response
            var response = new ChessGameRegistrationResponse(
                    registrationId,
                    true,
                    "Game registered to platform successfully",
                    gameId
            );
            
            log.info("ACL: Chess game registered successfully - gameId={}, registrationId={}", 
                    gameId, response.getRegistrationId());
            
            return ResponseEntity.status(HttpStatus.CREATED).body(response);
            
        } catch (Exception e) {
            log.error("ACL: Error registering chess game: gameId={}", gameId, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ChessGameRegistrationResponse(
                            null,
                            false,
                            "Failed to register chess game: " + e.getMessage(),
                            gameId
                    ));
        }
    }
    
    /**
     * Helper method to create a chess achievement.
     */
    private ChessGameRegisteredMessage.ChessAchievement createAchievement(String code, String description) {
        ChessGameRegisteredMessage.ChessAchievement achievement = new ChessGameRegisteredMessage.ChessAchievement();
        achievement.setCode(code);
        achievement.setDescription(description);
        return achievement;
    }

    /**
     * Get chess game information.
     * 
     * Note: Chess game state is managed by external chess service, not game-service.
     * This endpoint should query the external chess service via API Gateway.
     * 
     * @param gameId The chess game ID
     * @return Game information
     */
    @GetMapping("/games/{gameId}")
    public ResponseEntity<?> getChessGame(@PathVariable UUID gameId) {
        log.debug("ACL: Getting chess game info - gameId={}", gameId);
        
        // Chess game state is managed by external chess service
        // This endpoint should be called via API Gateway which routes to external chess service
        // For now, return a placeholder response
        // In a full implementation, this would query game registry metadata
        
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED)
                .body(Map.of(
                    "message", "Chess game queries should go through API Gateway to external chess service",
                    "gameId", gameId.toString()
                ));
    }
}
