import { ApiService } from './api.service'
import { API_ENDPOINTS } from '../config/api.config'
import type { RegisterChessGameRequest } from '../types/chess.types'

const { CHESS } = API_ENDPOINTS

export interface ChessGameRegistrationResponse {
  success: boolean
  message: string
  data: string // registrationId
  gameId: string // Generated by gateway
}

class ChessService extends ApiService {
  /**
   * Register a chess game with the platform
   * The gateway will generate a gameId (UUID) automatically
   * The gameId is returned in the response
   */
  async registerGame(data: RegisterChessGameRequest) {
    return this.post<ChessGameRegistrationResponse>(CHESS.REGISTER, data)
  }
}

export const chessService = new ChessService();

